package opengpu.v2.ocsl;

import java.util.List;

/**
 * Writes the golden vector file. Run deliberately; never from a test.
 *
 * <pre>
 *   ./gradlew ocslGolden
 * </pre>
 *
 * WRITES THE FILE ITSELF rather than printing for the shell to redirect, and that is not
 * fastidiousness. The first version printed to stdout and the task was invoked as
 * {@code gradlew -q ocslGolden > …}; FPGradle prints a "new version is available" notice to
 * STDOUT, which {@code -q} does not suppress, so six lines of build chatter landed in the middle
 * of the artifact and the checker died on "line 151 has no '->'". Any generator whose output is a
 * checked-in file should own the file handle; a build tool's stdout is shared and not yours.
 *
 * SEPARATE FROM THE TEST ON PURPOSE. If the checker could regenerate its own expectations — behind
 * a flag, an "update" mode, a missing-file fallback — then the first response to a red build would
 * be to regenerate, and the suite would pin nothing. There is no such path: {@link OcslGoldenTest}
 * only ever reads and compares, and fails loudly if the file is absent.
 *
 * The correct workflow when the file and the code disagree is to look at the diff and decide which
 * one is wrong. Usually it is the code. When it genuinely is the file — a domain row was
 * deliberately changed — regenerate, and the review sees exactly which values moved.
 */
public final class OcslGoldenGenerator {
	private OcslGoldenGenerator() {}

	public static void main(String[] args) throws java.io.IOException {
		if (args.length != 1) {
			throw new IllegalArgumentException("usage: OcslGoldenGenerator <output-file>");
		}
		StringBuilder out = new StringBuilder();
		out.append("# OCSL golden vectors -- format 1\n");
		out.append("#\n");
		out.append("# GENERATED by OcslGoldenGenerator. Do not hand-edit: regenerate and review the\n");
		out.append("# diff. Every value here is a FROZEN semantic choice from the A4 domain table,\n");
		out.append("# not an observation of what the code happens to do -- a line that moves is a\n");
		out.append("# change to the language, and every OCSL program's output moves with it.\n");
		out.append("#\n");
		out.append("# Values are raw float32 bit patterns, so 0.0 and -0.0 stay distinct and a\n");
		out.append("# one-ulp drift is a visible character change. Text after ';' is for the reader\n");
		out.append("# and is ignored by the parser.\n");
		out.append("#\n");
		out.append("# NOT COVERED HERE, and each for a stated reason:\n");
		// sample() USED to be excluded here, on the grounds that the CPU VM had no texture.
		// It has one, and the 24 sample: rows below are its output -- the exclusion outlived
		// its reason and was still being re-emitted on every regeneration until 2026-08-23.
		out.append("#   whole-program pixel values -- a pixel from a program with a fetch depends on\n");
		out.append("#                the texture the HOST bound, which is not part of the language.\n");
		out.append("#                (The reason recorded here until 2026-08-23 was the sampler being a\n");
		out.append("#                stub returning zero. It is not: OcslMath.sample does real bilinear\n");
		out.append("#                work, pinned by the 24 sample: rows below, and an UNBOUND slot\n");
		out.append("#                reading 0 is frozen rule S5, not a stub.)\n");
		out.append("#   atan2(0,0) on the GPU -- the CPU value is pinned below at 0 per amendment\n");
		out.append("#                1, but GLSL leaves atan(0,0) implementation-defined, so this\n");
		out.append("#                row is excluded from the Stage D cross-backend comparison\n");
		out.append("#                rather than from this file. See DESIGN.\n");
		out.append("#\n");

		List<OcslGolden.Case> cases = OcslGolden.cases();
		for (int i = 0; i < cases.size(); i++) {
			OcslGolden.Case c = cases.get(i);
			float[] result = OcslGolden.evaluate(c.op, c.args);
			if (result.length != OcslGolden.resultWidth(c.op)) {
				throw new IllegalStateException("op " + c.op + " produced " + result.length
						+ " components, expected " + OcslGolden.resultWidth(c.op));
			}
			out.append(OcslGolden.line(c, result)).append('\n');
		}
		out.append("# ").append(cases.size()).append(" vectors\n");

		java.io.File target = new java.io.File(args[0]);
		java.io.File parent = target.getParentFile();
		if (parent != null && !parent.isDirectory() && !parent.mkdirs()) {
			throw new java.io.IOException("cannot create " + parent);
		}
		// Explicit UTF-8 and explicit \n: the file is compared byte for byte by reviewers, and a
		// platform default that turned every line ending into \r\n on this Windows host would show
		// up as a whole-file diff the next time anyone regenerated it on Linux.
		java.io.Writer w = new java.io.OutputStreamWriter(
				new java.io.FileOutputStream(target), "UTF-8");
		try {
			w.write(out.toString());
		} finally {
			w.close();
		}
		System.out.println("wrote " + cases.size() + " vectors to " + target);
	}
}
