package opengpu.v2.ocsl;

/**
 * Renders the three FREEZE-GATED TABLES as text, from the code that implements them.
 *
 * <h2>Why these exist as a checked-in file and not as prose</h2>
 *
 * The roadmap names three tables as freeze-gated — the per-surface reserved register/id table (which
 * DESIGN calls "a Stage B deliverable before any blob is written"), the constructor arity table, and
 * the op-accounting/charge table. An audit on 2026-08-12 found that <b>two of the three existed only
 * as prose and Java</b>; the third had become a real table that same day. The point of calling them
 * freeze-gated is that a SECOND implementer — the Stage D GLSL backend — must be able to assign the
 * same ids, accept the same constructor arities and charge the same op counts without reading this
 * package's source. Prose scattered across three paragraphs of a design document does not support
 * that, and the design document is not even shipped: {@code docs/} is gitignored, so a table written
 * there reaches nobody outside this working copy.
 *
 * So the tables are emitted here and frozen in {@code src/test/resources/ocsl/surface-tables.txt},
 * exactly as the golden vectors are: generated by a separate main, compared by a test that can only
 * read. That gives them the two properties prose never had — they SHIP, and they are ENFORCED. A
 * reserved id silently changing its number is the failure the whole reservation discipline exists to
 * prevent, and until now nothing would have caught it.
 *
 * <h2>What the file is, and is not</h2>
 *
 * It is a statement of FROZEN CONTRACT, not an observation. Every line is a choice a saved blob
 * depends on: an id that moves invalidates blobs written under the old number, an arity that
 * loosens changes what a program may say, and a charge that changes moves every committed acceptance
 * count. A diff here is a format decision, and should be read as one.
 *
 * It deliberately does NOT carry the numeric domain table (that is the golden vectors' job) or the
 * CPU weight column (a measurement, not a contract — and one that moved by 2x under a JIT artifact
 * the same day, which is exactly why it is not frozen anywhere).
 */
public final class OcslTables {
	private OcslTables() {}

	/**
	 * Every stage the wire knows, not only the four with property tables.
	 *
	 * DERIVED by walking the stage id space, because the hand-kept version rendered identically when
	 * {@code STAGE_VERTEX} was given a readable register — and the file meanwhile asserted that an
	 * all-dashes row means "reserved and unreadable". Rendering four of seven stages while claiming
	 * that is how a file states the opposite of the truth without anything noticing.
	 */
	private static byte[] knownStages() {
		int n = 0;
		for (int s = 0; s <= 255; s++) {
			if (OcslWire.isKnownStage((byte) s)) {
				n++;
			}
		}
		byte[] stages = new byte[n];
		int at = 0;
		for (int s = 0; s <= 255 && at < n; s++) {
			if (OcslWire.isKnownStage((byte) s)) {
				stages[at++] = (byte) s;
			}
		}
		return stages;
	}

	private static String stageName(byte stage) {
		switch (stage) {
			case OcslWire.STAGE_PIXEL_MATERIAL: return "material";
			case OcslWire.STAGE_PIXEL_EFFECT: return "effect";
			case OcslWire.STAGE_PIXEL_POST: return "post";
			case OcslWire.STAGE_BAKE: return "bake";
			case OcslWire.STAGE_VERTEX: return "vertex";
			case OcslWire.STAGE_ANIMATOR: return "animator";
			case OcslWire.STAGE_COMPUTE: return "compute";
			default: throw new IllegalStateException("stage " + (stage & 0xFF) + " is known to the"
					+ " wire but has no name here; a stage added without a name would render as a"
					+ " column nobody can identify");
		}
	}

	public static String render() {
		StringBuilder out = new StringBuilder();
		header(out);
		registerTable(out);
		propertyTable(out);
		slotTable(out);
		constructorTable(out);
		opTable(out);
		blockTable(out);
		notFrozenHere(out);
		return out.toString();
	}

	private static void header(StringBuilder out) {
		line(out, "# OCSL freeze-gated tables -- format 1");
		line(out, "#");
		line(out, "# GENERATED by OcslTablesGenerator. Do not hand-edit: regenerate and read the");
		line(out, "# diff. Every line is a FROZEN CONTRACT a saved blob depends on, not an");
		line(out, "# observation of what the code happens to do. A register id that moves");
		line(out, "# invalidates every blob written under the old number; a charge that moves");
		line(out, "# moves all four committed acceptance counts.");
		line(out, "#");
		line(out, "# This file freezes the three tables the roadmap gates the format freeze on:");
		line(out, "# per-surface register ids, constructor arity, and op accounting. It exists");
		line(out, "# because the design document cannot serve the role -- docs/ is gitignored and");
		line(out, "# does not ship.");
		line(out, "#");
		line(out, "# IT IS NOT A COMPLETE FORMAT SPECIFICATION, and the first cut of this header");
		line(out, "# said it was. An adversarial pass applied seven format-breaking mutations at");
		line(out, "# once -- a colliding built-in id, PROP_COLOR renumbered, the operand tag bit");
		line(out, "# moved, swizzle packing changed, MAX made strict instead of broadcasting, the");
		line(out, "# input sampler extended to bake, a readable register added to the vertex stage");
		line(out, "# -- and this file rendered BYTE-IDENTICAL to all of them. Four of those are now");
		line(out, "# covered; the rest are listed under [not-frozen-here] at the end, because a");
		line(out, "# frozen artifact that overstates its coverage is worse than none.");
		line(out, "#");
		line(out, "#   ./gradlew ocslTables    regenerate");
		line(out, "");
	}

	/**
	 * TABLE 1 — the per-surface reserved register/id table.
	 *
	 * Reserved-but-unreadable ids are carried explicitly as {@code -} across every stage rather than
	 * omitted, because that is the entire content of a reservation: {@code timePeriod} at id 8 and
	 * {@code normal} at id 9 are here precisely BECAUSE nothing reads them, and a later assignment
	 * of those numbers to something else is the collision the discipline prevents.
	 */
	private static void registerTable(StringBuilder out) {
		byte[] stages = knownStages();
		StringBuilder stageHeader = new StringBuilder();
		StringBuilder ids = new StringBuilder();
		for (int s = 0; s < stages.length; s++) {
			stageHeader.append(' ').append(stageName(stages[s]));
			ids.append(s > 0 ? " " : "").append(stageName(stages[s])).append('=')
					.append(stages[s] & 0xFF);
		}
		line(out, "[stages] " + ids);
		line(out, "# The stage byte a blob carries. Absent from the first cut of this file, which");
		line(out, "# made it impossible to decode a blob's stage field from the table alone.");
		line(out, "");

		// OPENNESS IS FROZEN HERE because the gate that decides it stopped being derivable from
		// anything else in this file. It used to be readable off `[properties] required`, which said
		// `yes` for exactly the four open surfaces -- so adding a surface to the open set moved this
		// artifact. Once the predicate became its own function, opening a stage changed no frozen
		// byte, and a clean `./gradlew ocslTables` diff would have read as "no contract moved" while
		// a whole surface went live.
		line(out, "[open] stage open");
		line(out, "# Whether a program may be built, validated or run on this surface at all.");
		line(out, "# SEPARATE from whether it mandates an output -- see [properties] required. The");
		line(out, "# animator is the surface that distinguishes them: it mandates nothing and is");
		line(out, "# shut, and its required set must stay empty even after it opens.");
		for (int s = 0; s < stages.length; s++) {
			line(out, stageName(stages[s]) + " "
					+ (SurfaceTable.isOpen(stages[s]) ? "yes" : "no"));
		}
		line(out, "");

		line(out, "[registers] id name" + stageHeader);
		line(out, "# type per stage, or - when the stage does not carry that register.");
		line(out, "# An id present with - everywhere is RESERVED AND UNREADABLE, and deliberately so.");
		line(out, "# Rows are DERIVED by scanning the id space against builtinType at every stage, so");
		line(out, "# a register added anywhere appears here whether or not anyone listed it.");
		// EVERY id in the built-in span, with no predicate deciding which are interesting.
		//
		// Reserved-and-unreadable ids are the entire content of a reservation, so they are carried
		// explicitly -- a row of all dashes is the point, not an omission. The predicate that used
		// to select rows bounded on the LAST id anyone had assigned, which meant an id claimed in
		// the animator's 36..47 headroom, or anywhere in the light block at 10..15, rendered this
		// file byte-identical. That is exactly the mutation class the header claims to cover, so
		// the selection is gone: 48 rows, always, named or not.
		for (int reg = 0; reg < SurfaceTable.BUILTIN_LIMIT; reg++) {
			StringBuilder row = new StringBuilder();
			row.append(reg).append(' ').append(SurfaceTable.builtinName(reg));
			for (int s = 0; s < stages.length; s++) {
				OcslType t = SurfaceTable.builtinType(stages[s], reg);
				row.append(' ').append(t == null ? "-" : t.display());
			}
			line(out, row.toString());
		}
		line(out, "");
	}

	/**
	 * TABLE 1b — the property id namespace, which OUT's `property` operand indexes.
	 *
	 * PER STAGE, and it has to be: property ids are a per-surface namespace, so id 0 is `COLOR` at
	 * a pixel stage and `x` at the animator. Rendering them in one flat list would have printed the
	 * animator's `x` under the name `COLOR`.
	 */
	private static void propertyTable(StringBuilder out) {
		byte[] stages = knownStages();
		line(out, "[properties] stage id name type required");
		line(out, "# What OUT's `property` operand means, in the stage's OWN namespace.");
		line(out, "# required: the stage refuses a program that does not write it.");
		for (int s = 0; s < stages.length; s++) {
			for (int prop = 0; prop < 32; prop++) {
				OcslType t = SurfaceTable.propertyType(stages[s], prop);
				if (t == null) {
					continue;
				}
				line(out, stageName(stages[s]) + " " + prop + " "
						+ SurfaceTable.propertyName(stages[s], prop) + " " + t.display() + " "
						+ (isRequired(stages[s], prop) ? "yes" : "no"));
			}
		}
		line(out, "# Animator ids with NO row are reserved without a type, deliberately: `z` (int)");
		line(out, "# and `visible` (bool) are not ownable in v1 -- neither interpolates, and IR bool");
		line(out, "# is conditions-only -- so their ids are held but no OUT may target them.");
		line(out, "animator " + OcslWire.PROP_ANIM_Z + " z reserved no");
		line(out, "animator " + OcslWire.PROP_ANIM_VISIBLE + " visible reserved no");
		line(out, "");
	}

	private static boolean isRequired(byte stage, int property) {
		int[] required = SurfaceTable.requiredProperties(stage);
		for (int i = 0; i < required.length; i++) {
			if (required[i] == property) {
				return true;
			}
		}
		return false;
	}

	/** TABLE 1c — sampler slots, whose namespace is separate from the registers'. */
	private static void slotTable(StringBuilder out) {
		byte[] stages = knownStages();
		StringBuilder withInput = new StringBuilder();
		for (int s = 0; s < stages.length; s++) {
			if (SurfaceTable.hasInputSampler(stages[s])) {
				withInput.append(withInput.length() > 0 ? "," : "").append(stageName(stages[s]));
			}
		}
		// P belongs in the artifact: a blob that reads register 8 depends on its value, and a second
		// backend reading only this file would have found the register's TYPE frozen and its
		// meaning nowhere. Note the freeze is a different KIND than the ids above -- P rides no
		// blob, so changing it is a behaviour change and not a format break.
		line(out, "[time] name value");
		line(out, "# The `time` production (ANIM-4) and the wrap period P (ANIM-5). Unlike every id");
		line(out, "# in this file, P is NOT encoded in a blob -- it is supplied at runtime through");
		line(out, "# the timePeriod register, so moving it costs no format bump.");
		line(out, "tickNanos " + OcslTime.TICK_NANOS);
		line(out, "periodTicks " + OcslTime.PERIOD_TICKS);
		line(out, "periodNanos " + OcslTime.PERIOD_NANOS);
		line(out, "periodSecondsBits 0x"
				+ Integer.toHexString(Float.floatToIntBits(OcslTime.PERIOD_SECONDS)).toUpperCase());
		line(out, "unit seconds");
		line(out, "clock render");
		line(out, "domain half-open-0-to-P");
		line(out, "producers 1");
		line(out, "");

		// ANIM-3. In the artifact because a second executor composing differently produces a
		// different picture from the same blob -- the dry run measured the two candidate readings
		// 17 logical units apart on a node with sx=1.5.
		line(out, "[composition] property rule identity");
		line(out, "# How an animator's output combines with the server-set base. add: disp=srv+out.");
		line(out, "# mul: disp=srv*out. replace: disp=out. quat: disp=q_srv*q_out normalized,");
		line(out, "# animator-local applied FIRST, components (x,y,z) vector and w scalar.");
		line(out, "# x and y compose IN THE PARENT'S FRAME -- they are NOT rotated by the server");
		line(out, "# transform. The base is narrowed to float32 BEFORE composing, so the result is a");
		line(out, "# pure function of what the VM saw and two clients cannot disagree on it.");
		for (int prop = 0; prop < 32; prop++) {
			int rule = OcslCompose.ruleFor(prop);
			if (rule < 0) {
				continue;
			}
			String name = SurfaceTable.propertyName(OcslWire.STAGE_ANIMATOR, prop);
			String ruleName = rule == OcslCompose.RULE_ADD ? "add"
					: rule == OcslCompose.RULE_MULTIPLY ? "mul"
							: rule == OcslCompose.RULE_QUATERNION ? "quat" : "replace";
			String identity = rule == OcslCompose.RULE_ADD ? "0"
					: rule == OcslCompose.RULE_MULTIPLY ? "1"
							: rule == OcslCompose.RULE_QUATERNION ? "0,0,0,1" : "none";
			line(out, name + " " + ruleName + " " + identity);
		}
		line(out, "# `none` is not an omission: tint REPLACES, so no output leaves the base alone.");
		line(out, "");

		// ANIM-9(b). Before the write boundary because a value arrives before it leaves, and the
		// two halves are only correct together -- each one's fallback is the other's input.
		line(out, "[ingress] site remedy");
		line(out, "# What happens to a value on its way IN. The rule binds EVERY stage, animator and");
		line(out, "# bake included. It was written under a 'non-finite values at the PIXEL STAGE'");
		line(out, "# heading whose own back-reference pointed at the WRITE rule, so nothing in the");
		line(out, "# design said so; every method on OcslIngress now takes no stage, which is the");
		line(out, "# enforced spelling of that sentence.");
		line(out, "constantPool refuse-the-program");
		line(out, "registerBinding substitute-zero");
		line(out, "animatorScalarBase substitute-composition-identity");
		line(out, "animatorTintBase substitute-white");
		line(out, "animatorRot3dBase substitute-identity-quaternion");
		line(out, "uniformSetCall not-implemented");
		line(out, "# Zero is the remedy for a BINDING and the wrong one for a BASE: a non-finite base");
		line(out, "# reaches an op, A4's catch-all zeroes the whole result, and mul(NaN,2) is 0 -- so a");
		line(out, "# multiplicative property collapses the node. The identity is what leaves the other");
		line(out, "# side intact, and it is the mirror of a rejected output falling back to the base.");
		line(out, "# The set-call may reject-and-retain because the uniform table is REPLICATED and the");
		line(out, "# retained value is then identical on every client. The executor may NOT: a frame is");
		line(out, "# per-client, so a retained value there is binding history -- the cross-frame state");
		line(out, "# ANIM-9(a) removed. No host-facing setUniform exists while the surface is shut, so");
		line(out, "# that row is a stated gap rather than an omission.");
		line(out, "");

		// ANIM-9. Beside the composition rule because that is where a reader goes looking for it,
		// and because the boundary applies to the COMPOSED value rather than the raw output.
		line(out, "[write-boundary] name value");
		line(out, "# What happens to a value on its way out. A non-finite animator output is");
		line(out, "# REJECTED and the frame displays the server base -- statelessly, by substituting");
		line(out, "# the property's identity, so a client that joined on the failing frame and one");
		line(out, "# that watched for a minute agree. The superseded 'previous value retained' rule");
		line(out, "# was the only cross-frame state in the design and the one place purity broke.");
		line(out, "# Finite out-of-range is CLAMPED, not rejected: it still carries intent.");
		line(out, "nonFinitePolicy reject-to-server-base");
		line(out, "rot3dReject identity-quaternion");
		line(out, "# rot3d gets its own row because identityFor THROWS for a quaternion, so the scalar");
		line(out, "# path could not express 'falls back to the server base' and did not: a non-finite");
		line(out, "# animator quaternion used to fall out of the norm guard as the identity ROTATION,");
		line(out, "# discarding q_srv too, and a node with a server rotation snapped upright.");
		line(out, "trsLimit " + OcslWriteBoundary.TRS_LIMIT);
		line(out, "colorClamp 0..1");
		line(out, "colorSteps " + OcslWriteBoundary.COLOR_STEPS);
		line(out, "colorRounding half-up");
		line(out, "colorOrder clamp-then-quantize");
		line(out, "# clamp-then-quantize is load-bearing, not a preference: the destination is a");
		line(out, "# packed 8-bit-per-channel int that does NOT saturate. (int)(1.5*255) is 382,");
		line(out, "# which is 0x17E, and shifted into the alpha byte it lands as 126 -- a dark flash");
		line(out, "# where the author asked for full brightness.");
		line(out, "");

		line(out, "[slots] name value");
		line(out, "# Sampler bindings are their own namespace, not registers.");
		line(out, "inputSlot " + SurfaceTable.SLOT_INPUT);
		line(out, "inputSamplerStages "
				+ (withInput.length() > 0 ? withInput.toString() : "-"));
		line(out, "");

		// ANIM-16: the animator's caps STATED rather than inherited. Rendered per stage because
		// two of them differ there, and "inherited" was exactly the thing the amendment refused.
		line(out, "[stage-caps] stage fetches uniformComponents");
		line(out, "# fetches 0 at the animator is a RULE: no sampler exists in its register set, so");
		line(out, "# a fetch names a resource the surface cannot bind. The 64-component uniform");
		line(out, "# budget is the GL floor and does not apply where nothing is lowered to GLSL;");
		line(out, "# the animator is bounded by the frame-width cap instead. Node property input");
		line(out, "# registers do NOT charge against either -- they are built-ins, not declarations.");
		for (int s = 0; s < stages.length; s++) {
			line(out, stageName(stages[s]) + " " + IrValidator.maxFetches(stages[s]) + " "
					+ IrValidator.maxUniformComponentsAt(stages[s]));
		}
		line(out, "");
	}

	/**
	 * TABLE 2 — constructor arity.
	 *
	 * Amendment 4 requires these to be encoded AS OPS so that validator counting matches the builder
	 * exactly; the arity is therefore part of the accounting, not only of the type system. Each row
	 * is the operand shape the validator accepts and the width it yields.
	 */
	private static void constructorTable(StringBuilder out) {
		line(out, "[constructors] op operands result charge");
		line(out, "# The shapes amendment 4 pins. `f` is a float operand, `vN` a vector of width N.");
		constructorRow(out, OcslWire.OP_SPLAT, "f+width", "v2..v4");
		constructorRow(out, OcslWire.OP_CONS2, "f,f", "v2");
		constructorRow(out, OcslWire.OP_CONS3, "f,f,f", "v3");
		constructorRow(out, OcslWire.OP_CONS4, "f,f,f,f", "v4");
		constructorRow(out, OcslWire.OP_CONS3_V2F, "v2,f", "v3");
		constructorRow(out, OcslWire.OP_CONS4_V3F, "v3,f", "v4");
		constructorRow(out, OcslWire.OP_CONS4_V2V2, "v2,v2", "v4");
		line(out, "# SWZ is not a constructor: it selects 1..4 components from an existing value and");
		line(out, "# its result width is the swizzle length, so it carries no fixed arity row.");
		line(out, "");
	}

	private static void constructorRow(StringBuilder out, byte opcode, String operands,
			String result) {
		OcslWire.Shape shape = OcslWire.shapeOf(opcode);
		line(out, shape.name + " " + operands + " " + result + " " + shape.structuralCharge);
	}

	/**
	 * TABLE 3 — op accounting: every opcode, its structural charge, and its operand kinds.
	 *
	 * The charge column is the one amendments 12/13 gate the freeze on, and it is the column that
	 * moves committed counts. {@code FOR} and {@code ENDFOR} charging 0 is not an oversight — the
	 * structural count is a POST-UNROLL count and unrolled GLSL emits nothing for loop control — and
	 * it is written down here so a second backend does not "fix" it.
	 */
	private static void opTable(StringBuilder out) {
		line(out, "[ops] opcode name charge dst kinds");
		line(out, "# charge: structural ops debited per EXECUTION (post-unroll). dst: does it write");
		line(out, "# a register. kinds: operand slots -- value/imm/property/slot/swizzle.");
		for (int i = 0; i <= 80; i++) {
			OcslWire.Shape shape = OcslWire.shapeOf((byte) i);
			if (shape == null) {
				continue;
			}
			StringBuilder row = new StringBuilder();
			row.append(i).append(' ').append(shape.name).append(' ')
					.append(shape.structuralCharge).append(' ')
					.append(shape.hasDst ? "dst" : "-").append(' ');
			if (shape.operandCount() == 0) {
				row.append('-');
			}
			for (int k = 0; k < shape.operandCount(); k++) {
				if (k > 0) {
					row.append(',');
				}
				row.append(kindName(shape.operandKinds[k]));
			}
			line(out, row.toString());
		}
		line(out, "");
	}

	/**
	 * The reserved BLOCKS, which are the half of the reservation discipline a per-id table cannot
	 * express: contiguous ranges taken now so a later surface does not have to carve its ids out of
	 * space something else has claimed.
	 */
	private static void blockTable(StringBuilder out) {
		line(out, "[blocks] name base limit");
		line(out, "# Half-open [base, limit). Claimed now, assigned later.");
		line(out, "light " + SurfaceTable.REG_LIGHT_BASE + " " + SurfaceTable.REG_LIGHT_LIMIT);
		line(out, "animator " + SurfaceTable.REG_ANIMATOR_BASE + " "
				+ SurfaceTable.REG_ANIMATOR_LIMIT);
		line(out, "uniform " + SurfaceTable.UNIFORM_BASE + " " + SurfaceTable.UNIFORM_LIMIT);
		line(out, "working " + SurfaceTable.WORKING_BASE + " " + SurfaceTable.MAX_REGISTERS);
		line(out, "");
		line(out, "[caps] name value");
		line(out, "# Most of these may be RAISED under the monotonicity rule and never lowered once");
		line(out, "# blobs exist. TWO EXCEPTIONS, because the blanket claim was wrong:");
		line(out, "#   maxUniforms  CANNOT be raised. It is uniformLimit - uniformBase, and");
		line(out, "#                uniformLimit == workingBase, so raising it either overlaps the");
		line(out, "#                working block or moves workingBase -- which renumbers every");
		line(out, "#                working register in every saved blob. Raising it is a format");
		line(out, "#                break, not a relaxation.");
		line(out, "#   maxRegisters may be raised only to the DECODER's own separate bound, which");
		line(out, "#                is not this number and is not in this file. Same simple name,");
		line(out, "#                different constant.");
		line(out, "maxRegisters " + SurfaceTable.MAX_REGISTERS);
		line(out, "maxFrameWidth " + SurfaceTable.MAX_FRAME_WIDTH);
		line(out, "maxSlots " + SurfaceTable.MAX_SLOTS);
		line(out, "maxUniforms " + SurfaceTable.MAX_UNIFORMS);
		line(out, "maxStructuralOps " + IrValidator.MAX_STRUCTURAL_OPS);
		line(out, "maxFetches " + IrValidator.MAX_FETCHES);
		line(out, "maxUnrollProduct " + IrValidator.MAX_UNROLL_PRODUCT);
		line(out, "maxUniformComponents " + IrValidator.MAX_UNIFORM_COMPONENTS);
	}

	/**
	 * What this file does NOT freeze — written into the artifact, not left in a review transcript.
	 *
	 * Each line is a contract a second backend genuinely needs and would not get here. Naming them
	 * costs nothing and is the difference between a partial gate and a misleading one; the same
	 * adversarial pass that proved these gaps also proved the header claiming otherwise was false.
	 */
	private static void notFrozenHere(StringBuilder out) {
		line(out, "[not-frozen-here] contract where-it-lives");
		line(out, "# Proved absent by mutation: each of these can change while this file renders");
		line(out, "# byte-identical. Do not read a silent diff as coverage.");
		line(out, "operand-tag-bit OcslWire.OPERAND_CONST_FLAG/OPERAND_INDEX_MASK");
		line(out, "swizzle-packing OcslWire.packSwizzle/swizzleComponent/swizzleLength");
		line(out, "broadcast-vs-strict IrValidator -- which ops broadcast a float operand");
		line(out, "splat-is-forbidden-where-broadcast-works IrValidator (forks the content hash)");
		line(out, "result-types-per-op [ops] carries no result column; LT and SUB render alike");
		line(out, "constructor-operand-ORDER [constructors] operand strings are literals, not derived");
		line(out, "decoder-caps OcslWire MAX_CONSTANTS/MAX_OPS/MAX_NAMES/MAX_BLOB_BYTES/etc");
		line(out, "blob-envelope OcslWire MAGIC/FORMAT_VERSION/TRAILING_GUARD");
		line(out, "uniform-binding-rule declaration order from uniformBase, all float in v1");
		line(out, "numeric-domain golden-vectors.txt (frozen there, deliberately not duplicated)");
		line(out, "isOpen-independence SurfaceTable -- see below, NOT behaviourally detectable");
		line(out, "#");
		line(out, "# That last one is an honest gap rather than an oversight. `isOpen` and");
		line(out, "# `requiredProperties(s).length != 0` return the same answer for all 256 stage");
		line(out, "# bytes TODAY, so re-deriving one from the other is a source-level regression with");
		line(out, "# no observable consequence -- no test and no frozen byte can catch it. It matters");
		line(out, "# because the day the animator opens they diverge, and re-coupling them puts back");
		line(out, "# the trap this split removed: clearing the validator gate by giving the animator");
		line(out, "# a required property, which forces every animator program to own it (ANIM-2).");
		line(out, "# If you are here to de-duplicate those two switches: don't.");
	}

	private static String kindName(int kind) {
		switch (kind) {
			case OcslWire.KIND_VALUE: return "value";
			case OcslWire.KIND_IMMEDIATE: return "imm";
			case OcslWire.KIND_PROPERTY: return "property";
			case OcslWire.KIND_SLOT: return "slot";
			case OcslWire.KIND_SWIZZLE: return "swizzle";
			default: throw new IllegalStateException("operand kind " + kind + " has no name here;"
					+ " a kind added to the wire must be added to this table or the frozen file"
					+ " silently stops describing the format");
		}
	}

	private static String join(String[] parts) {
		StringBuilder b = new StringBuilder();
		for (int i = 0; i < parts.length; i++) {
			if (i > 0) {
				b.append(' ');
			}
			b.append(parts[i]);
		}
		return b.toString();
	}

	/** Newline written explicitly, so the file is byte-identical on every platform. */
	private static void line(StringBuilder out, String text) {
		out.append(text).append('\n');
	}
}
